# Generated by Django 5.0.6 on 2024-05-20 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="lesson",
            new_name="course",
        ),
    ]
